//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplainCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complain
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> ResolvedById { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<int> AssignedById { get; set; }
        public Nullable<int> AssignedToId { get; set; }
        public Nullable<int> ComplainById { get; set; }
        public Nullable<int> UpdateById { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> ComplainDate { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ComplainStatusId { get; set; }
        public Nullable<int> PCId { get; set; }
    
        public virtual ComplainStatus ComplainStatus { get; set; }
        public virtual Location Location { get; set; }
        public virtual PC PC { get; set; }
        public virtual User Resolver { get; set; }
        public virtual User Assigner { get; set; }
        public virtual User Assignee { get; set; }
        public virtual User Complainer { get; set; }
        public virtual User Updater { get; set; }
    }
}
