//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplainCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        public PC()
        {
            this.Complains = new HashSet<Complain>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> PCStatusId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Complain> Complains { get; set; }
        public virtual PCStatus PCStatus { get; set; }
    }
}
