//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplainCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCStatus
    {
        public PCStatus()
        {
            this.PCs = new HashSet<PC>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PC> PCs { get; set; }
    }
}
